-- ============================================================================
-- 全球图书馆知识与信息服务平台 Global Library Knowledge & Information Platform
-- 第五阶段：数据库设计 V0.2 —— **PostgreSQL 方言转换版**
-- 切片范围：Country / Library（Issue 001 Library Dynamic Vertical Slice）
--
-- 来源：05_Database_Design/V0.2/08-schema.sql（SQLite 3 方言）
-- 规则：**只允许 dialect compatibility conversion，不允许改变数据模型语义**
--      表名、字段、顺序、NOT NULL、DEFAULT、CHECK、UNIQUE、FK 行为、索引全部等价。
--
-- 转换清单（逐条对应原始 SQLite 定义）：
--   T1  INTEGER PRIMARY KEY AUTOINCREMENT
--         → INTEGER GENERATED **BY DEFAULT** AS IDENTITY PRIMARY KEY
--           选 BY DEFAULT 而非 ALWAYS：迁移必须显式写入原始 library_id / country_id
--           （SQLite 的 AUTOINCREMENT 同样允许显式插入整数 PK，语义等价）
--   T2  TEXT（逻辑 DATETIME）→ TIMESTAMPTZ，DEFAULT now()  ← 对应 datetime('now')
--   T3  REAL（latitude / longitude）
--         → DOUBLE PRECISION
--           原始文件注释建议 NUMERIC(8,5)；此处改用 DOUBLE PRECISION，
--           因为 pg 驱动会把 NUMERIC 序列化为**字符串**，
--           会破坏 world-map.js 中 project(lng, lat) 的数值投影与前台渲染。
--           数值取值集合完全相同（-90..90 / -180..180 + CHECK 保留），无语义变化。
--   T4  VARCHAR(n) 长度按原注释逐字段恢复（SQLite 不强制长度，此处为意图复原）
--   T5  CHECK / UNIQUE / FK（RESTRICT、CASCADE、UPDATE CASCADE）/ 四条索引全部保留
--
-- 未包含：Award / Award_Result / Case_Project / Source / *_source
--         本轮不是它们的业务切片，继续由 data/*.json 提供。
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Country 国家/地区
-- ---------------------------------------------------------------------------
CREATE TABLE country (
    country_id   INTEGER           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name VARCHAR(100)      NOT NULL,                     -- 国家/地区名称
    country_code VARCHAR(2)        NOT NULL UNIQUE,              -- ISO 3166-1 alpha-2
    region       VARCHAR(20)       NOT NULL
                 CHECK (region IN ('Asia','Europe','North America','South America','Africa','Oceania')),
    description  TEXT,                                           -- 国家/地区概况
    latitude     DOUBLE PRECISION  CHECK (latitude  IS NULL OR (latitude  BETWEEN -90   AND 90)),
    longitude    DOUBLE PRECISION  CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
    status       VARCHAR(20)       NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft','pending','published')),
    last_updated TIMESTAMPTZ       NOT NULL,
    created_at   TIMESTAMPTZ       NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2. Library 图书馆
-- ---------------------------------------------------------------------------
CREATE TABLE library (
    library_id   INTEGER           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)      NOT NULL,                     -- 图书馆名称（官方名称/中文名）
    name_en      VARCHAR(255),                                   -- V0.2 CHG-001，允许空
    country_id   INTEGER           NOT NULL
                 REFERENCES country(country_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    city         VARCHAR(100),
    library_type VARCHAR(20)       NOT NULL
                 CHECK (library_type IN ('national','public','academic','school','special','other')),
    description  TEXT,
    website      VARCHAR(500),
    latitude     DOUBLE PRECISION  CHECK (latitude  IS NULL OR (latitude  BETWEEN -90   AND 90)),
    longitude    DOUBLE PRECISION  CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
    founded_year INTEGER           CHECK (founded_year IS NULL OR (founded_year BETWEEN 1000 AND 2100)),
    status       VARCHAR(20)       NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft','pending','published')),
    last_updated TIMESTAMPTZ       NOT NULL,
    created_at   TIMESTAMPTZ       NOT NULL DEFAULT now()
);

CREATE INDEX idx_library_name    ON library(name);
CREATE INDEX idx_library_country ON library(country_id);
CREATE INDEX idx_library_status  ON library(status);
CREATE INDEX idx_library_type    ON library(library_type);

COMMIT;
