-- ============================================================
-- 由 db/seed/generate-seed.py 自动生成 —— 请勿手改
-- 生成时间：2026-10-02 20:49:44
-- 数据源：data/countries.json、data/libraries.json（Stage8-v1.0 冻结基线）
-- Country = 22；Library = 61（published 59 / pending 1 / draft 1）
-- 显式写出主键 ID，保证与 JSON 一致
-- ============================================================

BEGIN;

-- ---------- Country ----------
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (1, '中国', 'CN', 'Asia', 'Pilot 与 Demo 数据集的核心样本国，涵盖国家馆、省级馆、高校馆与城市/区县级公共图书馆四级体系；2024 年北京城市图书馆获 IFLA 年度公共图书馆奖，为中国首次。', 35.0, 105.0, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (2, '美国', 'US', 'North America', '拥有大型公共图书馆系统与国家图书馆体系；样本含纽约公共图书馆、国会图书馆、布鲁克林公共图书馆、米苏拉公共图书馆等，覆盖 IFLA 与 ALA/AIA 两类奖项。', 39.8, -98.6, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (3, '丹麦', 'DK', 'Europe', '公共图书馆传统深厚，2016 年年度公共图书馆奖由奥胡斯 Dokk1 获得；丹麦皇家图书馆为国家图书馆。', 56.0, 10.0, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (4, '西班牙', 'ES', 'Europe', '2023 年巴塞罗那加西亚·马尔克斯图书馆获 IFLA 年度公共图书馆奖，为西班牙图书馆首次入围并获奖。', 40.4, -3.7, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (5, '芬兰', 'FI', 'Europe', '公共图书馆法与全民阅读传统成熟；2019 年赫尔辛基中央图书馆 Oodi 获 IFLA 年度公共图书馆奖。', 64.0, 26.0, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (6, '挪威', 'NO', 'Europe', '2021 年奥斯陆 Deichman Bjørvika 获 IFLA 年度公共图书馆奖，以被动房标准与城市文化客厅定位著称。', 61.0, 8.5, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (7, '加拿大', 'CA', 'North America', '2025 年魁北克市加布里埃尔·罗伊图书馆获 IFLA 年度公共图书馆奖，以既有建筑更新与社区共同设计为特色。', 56.1, -106.3, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (8, '荷兰', 'NL', 'Europe', '2018 年登海尔德 School 7（KopGroep 图书馆）获 IFLA 年度公共图书馆奖，为荷兰图书馆首次获奖。', 52.1, 5.3, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (9, '瑞典', 'SE', 'Europe', '2015 年斯德哥尔摩 Kista 公共图书馆获 IFLA 年度公共图书馆奖；北欧 kulturhus（文化之家）理念对多国图书馆产生影响。', 60.1, 18.6, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (10, '澳大利亚', 'AU', 'Oceania', '2014 年首届 IFLA 年度公共图书馆奖由墨尔本北郊休姆市 Craigieburn 图书馆（休姆全球学习中心）获得。', -25.3, 133.8, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (11, '墨西哥', 'MX', 'North America', '2016 年首届 IFLA 绿色图书馆奖由恰帕斯州“小太阳生态图书馆”获得，该馆由学校与家长社区以回收材料共建。', 23.6, -102.6, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (12, '哥伦比亚', 'CO', 'South America', '公共图书馆网络活跃，2016、2019、2023 年三度进入 IFLA 绿色图书馆奖获奖名单（麦德林公共图书馆系统、卡利丹尼尔吉拉德市政图书馆、麦德林 EPM 图书馆）。', 4.6, -74.3, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (13, '德国', 'DE', 'Europe', '绿色图书馆实践突出，巴特奥尔斯洛市图书馆获 2017 年 IFLA 绿色图书馆奖；德国国家医学图书馆获 2011 年 IFLA 国际营销奖。', 51.2, 10.4, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (14, '泰国', 'TH', 'Asia', '兰实大学图书馆以可持续环境管理项目获 2020 年 IFLA 绿色图书馆奖。', 15.9, 101.0, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (15, '新加坡', 'SG', 'Asia', '新加坡国家图书馆管理局曾获 2009 年 IFLA 国际营销奖，2022 年以蔡厝港公共图书馆更新获 IFLA 绿色图书馆奖。', 1.35, 103.8, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (16, '法国', 'FR', 'Europe', '2022 年卡诺埃佩尔媒体图书馆获 IFLA 绿色图书馆奖项目类别第一名，为巴黎公共图书馆网络的可持续发展试点。', 46.6, 2.5, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (17, '爱沙尼亚', 'EE', 'Europe', '塔尔图大学图书馆获 2007 年与 2013 年 IFLA 国际营销奖第一名。', 58.6, 25.0, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (18, '印度', 'IN', 'Asia', '印度商学院学习资源中心获 2010 年 IFLA 国际营销奖第一名（信息工具产品线“知识伴侣”）。', 22.4, 78.9, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (19, '捷克共和国', 'CZ', 'Europe', '伊日·马亨图书馆获 2014 年 IFLA 国际营销奖第一名（“电车上的图书馆”项目）。', 49.8, 15.5, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (20, '肯尼亚', 'KE', 'Africa', '纳库鲁地区以“阅读树”项目获 2017 年 IFLA 绿色图书馆奖并列第二名，为撒哈拉以南非洲图书馆绿色教育实践的代表。', 0.2, 37.9, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (21, '新西兰', 'NZ', 'Oceania', '奥克兰市议会图书馆获 2024 年 IFLA 国际营销奖第一名（“拥有图书证的 100 个理由”）。', -41.0, 174.0, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO country (country_id, country_name, country_code, region, description, latitude, longitude, status, last_updated, created_at) VALUES (22, '爱尔兰', 'IE', 'Europe', '都柏林大学学院詹姆斯·乔伊斯图书馆以“超越生命周期：支持循环经济”获 2024 年 IFLA 绿色图书馆奖项目类别第一名。', 53.4, -8.2, 'published', '2026-09-19', '2026-09-19T04:00:00');

-- ---------- Library ----------
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (1, '上海图书馆', 'Shanghai Library', 1, '上海', 'public', '上海图书馆（上海科学技术情报研究所）馆所合一，1952年7月22日开馆，国家一级图书馆；2022年9月28日东馆开馆，为国内单体建筑面积最大的图书馆之一。2019年成立上海市中心图书馆体系，长期开展阅读推广与数字人文服务。', 'https://www.library.sh.cn', NULL, NULL, 1952, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (2, '中国国家图书馆', 'National Library of China', 1, '北京', 'national', '国家总书库、国家书目中心、国家古籍保护中心；前身为1909年9月9日获准设立的京师图书馆，1998年定现名；馆舍总面积28万平方米。', 'https://www.nlc.cn', NULL, NULL, 1909, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (3, '清华大学图书馆', 'Tsinghua University Library', 1, '北京', 'academic', '前身为1912年设立的清华学校图书室；现形成总馆与文科、美术、金融、法律、经管、建筑六个专业分馆的三级文献保障体系，馆藏总量超600万册件。', 'https://lib.tsinghua.edu.cn', NULL, NULL, 1912, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (4, '北京城市图书馆', 'Beijing Library', 1, '北京（城市副中心通州区）', 'public', '2023年12月开放，由 Snøhetta 与 ECADi 联合设计，建筑面积约7.5万平方米，拥有世界最大恒温阅览空间；采用模块化组件、气候控制与雨水回收等可持续方案，达中国绿色建筑三星标准。2024年10月获 IFLA 年度公共图书馆奖，为中国首次；2025年获 IFLA 国际营销奖第二名（“阅读花园”项目，与首都图书馆共同申报）。', NULL, NULL, NULL, 2023, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (5, '深圳市盐田区图书馆', 'Shenzhen Yantian District Library', 1, '深圳（盐田区）', 'public', '区级公共图书馆，纳入深圳“图书馆之城”总分馆体系。其“生长图书馆：万物皆可读，万物皆生长”项目2024年开放于盐田区生物圈三号·大梅沙万科中心碳中和实验园区，2025年获第十届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第二名，为本类别亚洲唯一获奖大型项目。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (6, '晋江市图书馆', 'Jinjiang Library', 1, '晋江（福建泉州）', 'public', '县级市公共图书馆，建设市级总分馆体系（共享全市272万册纸质图书）。其英林分馆“绿荫里图书馆”2025年3月开放于英林镇长存公园，由闲置旧屋微改造而成，2026年获第11届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别全球第二名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (7, '纽约公共图书馆', 'The New York Public Library', 2, 'New York City', 'public', '1895年由阿斯特图书馆、莱诺克斯图书馆与蒂尔登信托合并而成，为美国最大的公共图书馆系统，在布朗克斯、曼哈顿和史泰登岛拥有92个馆点，馆藏超5600万件。', 'https://www.nypl.org', NULL, NULL, 1895, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (8, '美国国会图书馆', 'Library of Congress', 2, 'Washington, D.C.', 'national', '1800年4月24日经约翰·亚当斯总统批准拨款建立，现为世界最大的图书馆、国会主要研究机构与美国版权局所在地，馆藏超1.62亿件。', 'https://www.loc.gov', NULL, NULL, 1800, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (9, '布鲁克林公共图书馆', 'Brooklyn Public Library', 2, 'New York City (Brooklyn)', 'public', '1896年经布鲁克林共同议会决议建立，现拥有61个分馆，服务270万布鲁克林居民；2021年发起 Books Unbanned 计划，2023年获 IFLA 国际营销奖第二名。', 'https://www.bklynlibrary.org', NULL, NULL, 1896, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (10, '米苏拉公共图书馆', 'Missoula Public Library', 2, 'Missoula（Montana）', 'public', '蒙大拿州米苏拉市县公共图书馆，新总馆2021年向公众开放，造价约3800万美元，是美国首个按北欧 kulturhus（文化之家）理念专门建造的图书馆，馆内共置四个社区机构（公共电视、家庭学习实验室、大学探索区与生活实验室）。2022年获 IFLA 年度公共图书馆奖，2023年获 AIA/ALA 图书馆建筑奖。', 'https://www.missoulapubliclibrary.org', NULL, NULL, 2021, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (11, '伍斯特公共图书馆', 'Worcester Public Library', 2, 'Worcester（Massachusetts）', 'public', '马萨诸塞州伍斯特市公共图书馆。2025年凭“三月猫咪通行证”（March Meowness）活动获 IFLA PressReader 国际营销奖第一名，该活动以提交猫咪照片抵扣逾期罚款，以极低成本实现服务推广与用户互动。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (12, '旧金山公共图书馆', 'San Francisco Public Library', 2, 'San Francisco', 'public', '旧金山公共图书馆系统，2018年获 Gale/LJ 年度图书馆（Library of the Year）称号，评审称其为全球公共图书馆的典范。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (13, '纳什维尔公共图书馆', 'Nashville Public Library', 2, 'Nashville（Tennessee）', 'public', '田纳西州纳什维尔与戴维森县公共图书馆。2017年获 Gale/LJ 年度图书馆称号；2025年其 Donelson 分馆（2024年6月开放，LEED 金级认证）获第十届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第三名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (14, '阿瑟顿图书馆', 'Atherton Library', 2, 'Atherton（California）', 'public', '加州阿瑟顿市公共图书馆，隶属圣马特奥县图书馆系统；建筑以零净能耗（zero net energy）为目标设计，是社区型的现代公共服务枢纽。2023年获 AIA/ALA 图书馆建筑奖。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (15, '沃本公共图书馆', 'Woburn Public Library', 2, 'Woburn（Massachusetts）', 'public', '马萨诸塞州沃本公共图书馆，在保留原历史建筑（H.H. Richardson 设计）基础上扩建约3.05万平方英尺，2023年获 AIA/ALA 图书馆建筑奖。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (16, '丹麦皇家图书馆', 'Royal Danish Library (Det Kgl. Bibliotek)', 3, 'Copenhagen', 'national', '1648年由腓特烈三世奠基，丹麦国家图书馆；2017年与丹麦国家暨大学图书馆合并组建现丹麦皇家图书馆（Det Kgl. Bibliotek），在哥本哈根与奥胡斯多地设馆。', 'https://www.kb.dk', NULL, NULL, 1648, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (17, 'Dokk1（奥胡斯主图书馆）', 'Dokk1', 3, 'Aarhus', 'public', '2015年6月开放的北欧最大公共图书馆，由 Schmidt Hammer Lassen 设计，集图书馆、市民服务中心与公共广场于一体；2016年获 IFLA 年度公共图书馆奖，为首个获奖的丹麦图书馆。', 'http://www.aakb.dk', NULL, NULL, 2015, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (18, '加布里埃尔·加西亚·马尔克斯图书馆', 'Biblioteca Gabriel García Márquez', 4, 'Barcelona（Sant Martí de Provençals）', 'public', '2022年5月28日开馆，由 Suma Arquitectura 设计，六层约4000平方米，为巴塞罗那第三大图书馆；以交错层压木结构营造温暖氛围并降低环境足迹，专藏拉丁美洲文学，并保存漫画家 Francisco Ibáñez 的档案。2023年获 IFLA 年度公共图书馆奖，为西班牙图书馆首次入围并获奖。', NULL, NULL, NULL, 2022, 'pending', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (19, '赫尔辛基中央图书馆 Oodi', 'Helsinki Central Library Oodi', 5, 'Helsinki', 'public', '2018年12月5日（芬兰独立日前夕）开放的中央图书馆，由 ALA Architects 设计，建筑面积约1.71万平方米；三层分别对应活跃的城市广场、多功能中间层与宁静的阅读层，公民阳台正对议会大厦，象征图书馆与公众和民主的联结；按近零能耗建筑（nZEB）标准建造。2019年获 IFLA 年度公共图书馆奖，开放首年接待310万访客。', NULL, NULL, NULL, 2018, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (20, '奥斯陆 Deichman Bjørvika 图书馆', 'Deichman Bjørvika', 6, 'Oslo', 'public', '奥斯陆新总馆，由 Lund Hagem 与 Atelier Oslo 设计，2020年6月18日向公众开放；六层空间含影院、录音棚、游戏室、儿童区与 Future Library 艺术项目，藏量约45万册，总建筑面积1.96万平方米（净面积1.356万平方米）；按被动房标准建造，首层全透明立面面向峡湾与歌剧院。2021年获 IFLA 年度公共图书馆奖。', 'https://deichman.no', NULL, NULL, 2020, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (21, '魁北克加布里埃尔·罗伊图书馆', 'Bibliothèque Gabrielle-Roy', 7, 'Québec City（Saint-Roch）', 'public', '2024年2月开放的魁北克市中央图书馆，由 Saucier + Perrotte 与 GLCRM 建筑事务所联合设计；通过改造并扩建既有建筑、最大限度减少拆除与新材需求体现可持续策略；四层设十个主题枢纽（音乐与电影、青少年、烹饪等），由与社区共同设计的流程形成。2025年获 IFLA 年度公共图书馆奖。', NULL, NULL, NULL, 2024, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (22, 'School 7（KopGroep 图书馆）', 'Bibliotheek School 7 (KopGroep Bibliotheken)', 8, 'Den Helder', 'public', '位于登海尔德市的公共图书馆，2016年开放，由1905年的第七市立学校校舍改造而来，“School 7”之名即源于此；与本地剧院、咖啡馆、历史协会与民众大学合作，被定位为“城市的客厅”。2018年获 IFLA 年度公共图书馆奖，为荷兰图书馆首次获奖。', NULL, NULL, NULL, 2016, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (23, '基斯塔图书馆', 'Kista bibliotek', 9, 'Stockholm（Kista）', 'public', '斯德哥尔摩基斯塔区公共图书馆，隶属斯德哥尔摩市图书馆体系，2015年获 IFLA 年度公共图书馆奖。', NULL, NULL, NULL, NULL, 'draft', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (24, '克雷吉本图书馆（休姆全球学习中心）', 'Craigieburn Library (Hume Global Learning Centre)', 10, 'Melbourne（Craigieburn, Hume City）', 'public', '位于墨尔本北郊休姆市 Craigieburn 的公共图书馆与学习中心，2012年建成，由 Francis-Jones Morehen Thorp 设计，建筑面积4640平方米；以就地取材的夯土墙为主要材料，内部整合美术馆、咖啡馆、托幼中心、计算机培训与多功能空间。2014年获首届 IFLA 年度公共图书馆奖。', NULL, NULL, NULL, 2012, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (25, '小太阳生态图书馆', 'The Little Sun Ecological Library', 11, '恰帕斯州', 'school', '由学生家长发起、学校组织共建的生态图书馆，以回收纸板、PET 塑料瓶、废金属、托盘与木材等作为建筑材料，并利用建筑内空间开展阅读与环保教育。2016 年获首届 IFLA 绿色图书馆奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (26, '巴特奥尔斯洛市图书馆', 'Stadtbibliothek Bad Oldesloe', 13, '巴特奥尔斯洛（Bad Oldesloe）', 'public', '德国石勒苏益格-荷尔斯泰因州巴特奥尔斯洛市公共图书馆。以“收获你的城市”（Ernte deine Stadt）项目融合城市园艺、创客空间与社区营造，并促成当地首个社区支持农业。2017 年获第二届 IFLA 绿色图书馆奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (27, '麦德林公共图书馆系统', 'Sistema de Bibliotecas Públicas de Medellín', 12, '麦德林（Medellín）', 'public', '哥伦比亚麦德林市公共图书馆网络，以“公园图书室”（Parques Biblioteca）体系著称，在馆区周边开展土地绿化与可食用植物种植。2016 年获首届 IFLA 绿色图书馆奖第三名；2023 年以“环游世界，走遍 26 个图书馆”获 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (28, '广东省立中山图书馆', 'Sun Yat-sen Library of Guangdong Province', 1, '广州', 'public', '广东省省级公共图书馆，馆舍经生态环保理念改造为绿色图书馆，并以展览与活动推动公众环境教育。2017 年获第二届 IFLA 绿色图书馆奖并列第二名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (29, '香港中文大学图书馆', 'The Chinese University of Hong Kong (CUHK) Library', 1, '香港', 'academic', '香港中文大学图书馆系统，将可持续发展写入图书馆战略，形成超出单幢绿色建筑的绿色策略。2017 年获第二届 IFLA 绿色图书馆奖并列第二名。（中国香港按其所属国家归入中国，不单列为 Country 记录。）', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (30, '佛山市图书馆', 'Foshan Library', 1, '佛山', 'public', '佛山市市级公共图书馆，新馆位于佛山新城、与周边景观融合，将可持续原则贯穿建筑设计、材料、管理与社区教育。2018 年获第三届 IFLA 绿色图书馆奖第一名（“佛山市图书馆的绿色实践”），2020 年获 IFLA 国际营销奖第一名（“邻里图书馆”），2023 年获 IFLA 国际营销奖第三名（“易本书”），2024 年获 IFLA 绿色图书馆奖项目类别第三名（“绿色阅读”）。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (31, '卡利丹尼尔吉拉德市政图书馆', 'Biblioteca Pública Municipal Daniel Guillard', 12, '卡利（Cali）', 'public', '哥伦比亚卡利市公共图书馆。以“盖亚——在我的图书馆里，地球也属于所有人”项目推动生态教育与社会包容。2019 年获第四届 IFLA 绿色图书馆奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (32, '埃德蒙顿公共图书馆', 'Edmonton Public Library', 7, '埃德蒙顿（Edmonton）', 'public', '加拿大埃德蒙顿市公共图书馆系统，以服务创新与社区参与著称。2020 年获第五届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (33, '兰实大学图书馆', 'Rangsit University Library', 14, '巴吞他尼府（Pathumthani）', 'academic', '泰国兰实大学图书馆，以可持续环境管理报告参与评选，覆盖资源使用、废弃物管理与环境教育。2020 年获第五届 IFLA 绿色图书馆奖项目类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (34, '杭州图书馆', 'Hangzhou Public Library', 1, '杭州', 'public', '杭州市市级公共图书馆，通过设立环保分馆推动城市环境教育。2020 年获第五届 IFLA 绿色图书馆奖项目类别并列第二名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (35, '深圳坪山图书馆', 'Pingshan Library (Shenzhen)', 1, '深圳（坪山区）', 'public', '深圳市坪山区公共图书馆，以绿色建筑设计与阅读推广结合的“绿色行动”入围。2020 年获第五届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别短名单。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (36, '奥卢市图书馆', 'Oulu City Library', 5, '奥卢（Oulu）', 'public', '芬兰奥卢市公共图书馆，环保实践覆盖馆藏、能源使用与物流，并制定可持续发展行动计划。2021 年获第六届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (37, '新加坡国家图书馆管理局', 'National Library Board Singapore', 15, '新加坡（中央区）', 'national', '新加坡国家图书馆管理局，统筹国家图书馆与公共图书馆网络。2009 年以“Go Library”多平台营销项目获 IFLA 国际营销奖第一名；2022 年以蔡厝港公共图书馆更新获 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (38, '卡诺埃佩尔媒体图书馆', 'Médiathèque de la Canopée', 16, '巴黎（Paris）', 'public', '巴黎第一区卡诺埃佩尔媒体图书馆，作为巴黎公共图书馆网络的可持续发展试点。2022 年获第七届 IFLA 绿色图书馆奖项目类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (39, 'EPM 图书馆', 'Biblioteca EPM', 12, '麦德林（Medellín）', 'special', '哥伦比亚麦德林 EPM 集团图书馆，以可持续发展教育为核心战略。2023 年获第八届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (40, '西温哥华纪念图书馆', 'West Vancouver Memorial Library', 7, '西温哥华（不列颠哥伦比亚省）', 'public', '加拿大不列颠哥伦比亚省西温哥华纪念图书馆，以“驻馆气候作家”项目联动社区气候行动。2023 年获第八届 IFLA 绿色图书馆奖项目类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (41, '都柏林大学学院詹姆斯·乔伊斯图书馆', 'UCD Library, James Joyce Building', 22, '都柏林（Dublin）', 'academic', '爱尔兰都柏林大学学院主图书馆。以“超越生命周期：支持循环经济的图书馆”项目获 2024 年第九届 IFLA 绿色图书馆奖项目类别第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (42, '肯尼亚国家图书馆服务-纳库鲁分馆', 'Kenya National Library Service - Nakuru', 20, '纳库鲁（Nakuru）', 'public', '肯尼亚国家图书馆服务纳库鲁分馆，自 2015 年起在六所公立小学推广儿童读书会，以“阅读树”涂鸦激励儿童阅读。2017 年获第二届 IFLA 绿色图书馆奖并列第二名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (43, '休斯敦公共图书馆', 'Houston Public Library', 2, 'Houston（Texas）', 'public', '美国得克萨斯州休斯敦市公共图书馆系统。2002 年以“读者卡的挑战”项目获首届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (44, '巴塞罗那图书馆联盟', 'Concorde de Biblioteques de Barcelona', 4, 'Barcelona', 'other', '西班牙巴塞罗那市公共图书馆协作网络。2003 年以“文学路径”项目获第二届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (45, '澳大利亚伊斯兰学院图书馆', 'The School Library of Australian Islamic College', 10, 'Perth', 'school', '澳大利亚伊斯兰学院图书馆。2004 年以“我来了，我看见了，我读了”项目获第三届 IFLA 国际营销奖第一名，面向移民家庭儿童开展阅读与数字素养活动。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (46, '斯派克尼瑟公共图书馆', 'Public Library of Spijkenisse', 8, 'Spijkenisse', 'public', '荷兰斯派克尼瑟市公共图书馆。2006 年以“我们想念你”明信片召回活动获第四届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (47, '塔尔图大学图书馆', 'Tartu University Library', 17, 'Tartu', 'academic', '爱沙尼亚塔尔图大学图书馆。2007 年以“夜间图书馆”与“妈妈学生图书馆项目”获第五届 IFLA 国际营销奖第一名；2013 年以“会说话的教科书”获第十一届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (48, '中央西部图书馆', 'Central West Libraries', 10, 'Orange（New South Wales）', 'public', '澳大利亚新南威尔士州中央西部地区公共图书馆网络。2008 年以在线课堂作业辅导项目“你做完功课了吗？”获第六届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (49, '印度商学院学习资源中心', 'Learning Resource Centre, Indian School of Business', 18, 'Hyderabad', 'academic', '印度商学院学习资源中心。2010 年以“知识结伴，提升自我”信息工具产品线获第八届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (50, '德国国家医学图书馆', 'German National Library of Medicine (ZB MED)', 13, 'Cologne', 'national', '德国国家医学图书馆（ZB MED）。2011 年以 MEDPILOT 与 GREENPILOT 科学检索门户的在线推广获第九届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (51, '伊日·马亨图书馆', 'Jiří Mahen Library', 19, 'Brno', 'public', '捷克布尔诺市伊日·马亨图书馆。2014 年与布尔诺公共交通公司合作，以“电车上的图书馆”项目获第十二届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (52, '温哥华公共图书馆', 'Vancouver Public Library', 7, 'Vancouver（British Columbia）', 'public', '加拿大温哥华市公共图书馆。2015 年设立数字媒体实验室 Inspiration Lab，2016 年以“灵感实验室启动运动”获第十三届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (53, '不列颠哥伦比亚大学图书馆', 'The University of British Columbia Library', 7, 'Vancouver（British Columbia）', 'academic', '加拿大不列颠哥伦比亚大学图书馆。2018 年以馆藏珍品《乔叟集》数字化涂色书活动获第十六届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (54, '莫纳什大学图书馆', 'Monash University Library', 10, 'Melbourne', 'academic', '澳大利亚莫纳什大学图书馆。2021 年与美国宾夕法尼亚州立大学图书馆合作，以“绝世食谱”项目获第十八届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (55, '宾夕法尼亚州立大学图书馆', 'Penn State University Libraries', 2, 'University Park（Pennsylvania）', 'academic', '美国宾夕法尼亚州立大学图书馆。2021 年与莫纳什大学图书馆合作，以“绝世食谱”项目获第十八届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (56, '亚拉图书馆', 'Yarra Libraries', 10, 'Melbourne（Yarra）', 'public', '澳大利亚墨尔本亚拉市公共图书馆网络。2022 年以社区参与式战略规划项目获第十九届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (57, '奥克兰市议会图书馆', 'Auckland Council Libraries', 21, 'Auckland', 'public', '新西兰奥克兰市议会图书馆网络。2024 年以“拥有图书证的 100 个理由”项目获第二十一届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (58, '厦门大学图书馆', 'Xiamen University Libraries', 1, '厦门', 'academic', '厦门大学图书馆。2013 年起为毕业生制作“圕·时光”个人阅读账单网站，2016 年获第十三届 IFLA 国际营销奖并列第二名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (59, '北京科技大学图书馆', 'Library of University of Science and Technology Beijing', 1, '北京', 'academic', '北京科技大学图书馆。以微信公众号“读书人：见‘微’知‘著’”原创书目推荐栏目获 2017 年第十四届 IFLA 国际营销奖第一名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (60, '北京大学附属小学图书馆', 'Peking University Elementary School Library', 1, '北京', 'school', '北京大学附属小学图书馆。以游戏化信息素养教育活动“点亮图书馆”获 2022 年第十九届 IFLA 国际营销奖并列第二名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO library (library_id, name, name_en, country_id, city, library_type, description, website, latitude, longitude, founded_year, status, last_updated, created_at) VALUES (61, '南京大学图书馆', 'Nanjing University Libraries', 1, '南京', 'academic', '南京大学图书馆。2024 年以师生共创的“图书馆的声音”歌曲项目获第二十一届 IFLA 国际营销奖第三名。', NULL, NULL, NULL, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');

-- identity 序列校正（后续手工新增从 MAX(id)+1 开始，避免撞 ID）
SELECT setval(pg_get_serial_sequence('country', 'country_id'),
              COALESCE((SELECT MAX(country_id) FROM country), 1));
SELECT setval(pg_get_serial_sequence('library', 'library_id'),
              COALESCE((SELECT MAX(library_id) FROM library), 1));

COMMIT;
