-- ============================================================================
-- 全球图书馆知识与信息服务平台 Global Library Knowledge & Information Platform
-- 第五阶段：数据库设计 V0.2 —— **PostgreSQL 方言转换版**
-- 切片范围：Award / Award_Result / Case_Project / Source + 五张来源关联表
--           （B2 — Remaining Core Data Migration，消除 Hybrid 数据源）
--
-- 来源：05_Database_Design/V0.2/08-schema.sql（SQLite 3 方言）第 3–11 节
-- 规则：**只允许 dialect compatibility conversion，不允许改变数据模型语义**
--      表名、字段、顺序、NOT NULL、DEFAULT、CHECK、UNIQUE、FK 行为、索引全部等价。
--
-- 转换清单（与 01-schema-country-library.postgresql.sql 完全一致）：
--   T1  INTEGER PRIMARY KEY AUTOINCREMENT
--         → INTEGER GENERATED **BY DEFAULT** AS IDENTITY PRIMARY KEY
--           （迁移必须显式写入原始 ID；SQLite AUTOINCREMENT 同样允许显式插入整数 PK）
--   T2  TEXT（逻辑 DATETIME）→ TIMESTAMPTZ，DEFAULT now()  ← 对应 datetime('now')
--   T2b TEXT（逻辑 DATE）    → DATE（publication_date / accessed_date）
--   T4  VARCHAR(n) 长度按原注释逐字段恢复
--   T5  CHECK / UNIQUE / FK（RESTRICT、CASCADE、UPDATE CASCADE）/ 索引全部保留
--
-- 说明：
--   - 五张 *_source 关联表**没有 status 字段**（V0.2 schema 即如此），
--     本轮不为它们新增 status：可见性沿用既有 schema 语义与前台 JOIN 逻辑。
--   - Award 与 Library 之间**不存在直接外键**，仅通过 award_result 关联（业务规则 3/4）。
--
-- 方案 A（人工批准）——关联表 surrogate primary key：
--   Directus 无法暴露「无单列主键」的集合（启动日志明确：
--   Collection "xxx_source" doesn't have a primary key column and will be ignored）。
--   V0.2 的五张关联表使用复合主键 (entity_id, source_id)，因此本轮做
--   **物理实现兼容调整**：
--     + id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY   ← 纯技术列，无业务含义
--     + 原复合主键降级为 UNIQUE (entity_id, source_id)            ← 关系唯一性约束不变
--     + 两个外键、ON DELETE CASCADE、CHECK(relation_type)、索引全部保留
--   业务关系语义（多对多关系集合、基数、可追溯性）**完全不变**；
--   surrogate id 不参与任何业务判断、迁移比对或前台渲染。
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 3. Award 奖项
-- ---------------------------------------------------------------------------
CREATE TABLE award (
    award_id         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_name       VARCHAR(255) NOT NULL,
    organizer        VARCHAR(255),                        -- 主办机构
    description      TEXT,
    official_website VARCHAR(500),
    founded_year     INTEGER      CHECK (founded_year IS NULL OR (founded_year BETWEEN 1800 AND 2100)),
    frequency        VARCHAR(20)  CHECK (frequency IS NULL OR frequency IN ('annual','biennial','irregular')),
    status           VARCHAR(20)  NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft','pending','published')),
    last_updated     TIMESTAMPTZ  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_award_name_organizer UNIQUE (award_name, organizer)
);

-- ---------------------------------------------------------------------------
-- 4. Award_Result 获奖记录（Award 与 Library 的关联实体）
-- ---------------------------------------------------------------------------
CREATE TABLE award_result (
    award_result_id INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id        INTEGER      NOT NULL
                    REFERENCES award(award_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    library_id      INTEGER      NOT NULL
                    REFERENCES library(library_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    year            INTEGER      NOT NULL CHECK (year BETWEEN 1900 AND 2100),
    category        VARCHAR(100) NOT NULL DEFAULT 'general',   -- V0.2 CHG-002
    result_type     VARCHAR(30)  NOT NULL
                    CHECK (result_type IN ('winner','runner_up','honorable_mention','shortlist','other')),
    project_name    VARCHAR(255),
    description     TEXT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'draft'
                    CHECK (status IN ('draft','pending','published')),
    last_updated    TIMESTAMPTZ  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_award_result UNIQUE (award_id, library_id, year, category, result_type)
);

CREATE INDEX idx_ar_award    ON award_result(award_id);
CREATE INDEX idx_ar_library  ON award_result(library_id);
CREATE INDEX idx_ar_year     ON award_result(year);
CREATE INDEX idx_ar_category ON award_result(category);
CREATE INDEX idx_ar_status   ON award_result(status);

-- ---------------------------------------------------------------------------
-- 5. Case_Project 案例/项目
-- ---------------------------------------------------------------------------
CREATE TABLE case_project (
    case_id      INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id   INTEGER      NOT NULL
                 REFERENCES library(library_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    title        VARCHAR(255) NOT NULL,
    topic        VARCHAR(30)  NOT NULL
                 CHECK (topic IN ('ai_technology','digital_service','reading_promotion','space_architecture',
                                  'children_service','community_service','sustainability',
                                  'accessibility_inclusion','other')),
    description  TEXT,
    year         INTEGER      CHECK (year IS NULL OR (year BETWEEN 1900 AND 2100)),
    project_url  VARCHAR(500),
    status       VARCHAR(20)  NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft','pending','published')),
    last_updated TIMESTAMPTZ  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_case_library ON case_project(library_id);
CREATE INDEX idx_case_topic   ON case_project(topic);
CREATE INDEX idx_case_status  ON case_project(status);

-- ---------------------------------------------------------------------------
-- 6. Source 信息来源
-- ---------------------------------------------------------------------------
CREATE TABLE source (
    source_id        INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name      VARCHAR(255) NOT NULL,
    source_type      VARCHAR(30)  NOT NULL
                     CHECK (source_type IN ('official_website','international_organization',
                                            'library_association','government','academic','news','other')),
    title            VARCHAR(500),                        -- 页面/文档标题
    url              VARCHAR(500) UNIQUE,                 -- 唯一；NULL 不参与唯一判断
    publisher        VARCHAR(255),
    publication_date DATE,
    accessed_date    DATE         NOT NULL,               -- 访问/核对日期
    language         VARCHAR(10),                         -- ISO 639-1
    status           VARCHAR(20)  NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft','pending','published')),
    last_updated     TIMESTAMPTZ  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_source_type ON source(source_type);

-- ---------------------------------------------------------------------------
-- 7-11. 来源关联表（方案B：专用关联表，实体 ↔ Source 多对多）
--       V0.2 schema 无 status 字段，本轮不新增。
--
--       【人工批准的 Known Issues #1 修复 — Surrogate Primary Key】
--       问题：Directus 无法暴露没有单列主键的集合
--             （启动日志：Collection "xxx_source" doesn't have a primary key column and will be ignored）
--             公开与管理员请求 /items/xxx_source 均返回 403。
--       修复：物理实现兼容调整 —— 新增技术性代理主键 id，
--             原复合主键 (实体ID, source_id) **完整降级保留为 UNIQUE 约束**。
--       语义保证（业务关系零变更）：
--         - 两个 FK、ON DELETE CASCADE 语义不变；
--         - (实体ID, source_id) 唯一性不变，重复关系仍被拒绝；
--         - entity ID / source ID / relation_type 取值与 JSON baseline 完全一致；
--         - 新增的 id 为技术列，不参与任何业务判断，不参与 JSON ↔ DB 比对。
-- ---------------------------------------------------------------------------
CREATE TABLE country_source (
    id            INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- surrogate technical PK
    country_id    INTEGER     NOT NULL REFERENCES country(country_id) ON DELETE CASCADE,
    source_id     INTEGER     NOT NULL REFERENCES source(source_id)   ON DELETE CASCADE,
    relation_type VARCHAR(20) CHECK (relation_type IS NULL OR relation_type IN ('primary','supplementary')),
    CONSTRAINT uq_country_source UNIQUE (country_id, source_id)
);

CREATE TABLE library_source (
    id            INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- surrogate technical PK
    library_id    INTEGER     NOT NULL REFERENCES library(library_id) ON DELETE CASCADE,
    source_id     INTEGER     NOT NULL REFERENCES source(source_id)   ON DELETE CASCADE,
    relation_type VARCHAR(20) CHECK (relation_type IS NULL OR relation_type IN ('primary','supplementary')),
    CONSTRAINT uq_library_source UNIQUE (library_id, source_id)
);

CREATE TABLE award_source (
    id            INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- surrogate technical PK
    award_id      INTEGER     NOT NULL REFERENCES award(award_id)     ON DELETE CASCADE,
    source_id     INTEGER     NOT NULL REFERENCES source(source_id)   ON DELETE CASCADE,
    relation_type VARCHAR(20) CHECK (relation_type IS NULL OR relation_type IN ('primary','supplementary')),
    CONSTRAINT uq_award_source UNIQUE (award_id, source_id)
);

CREATE TABLE award_result_source (
    id              INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- surrogate technical PK
    award_result_id INTEGER   NOT NULL REFERENCES award_result(award_result_id) ON DELETE CASCADE,
    source_id       INTEGER   NOT NULL REFERENCES source(source_id)             ON DELETE CASCADE,
    relation_type   VARCHAR(20) CHECK (relation_type IS NULL OR relation_type IN ('primary','supplementary')),
    CONSTRAINT uq_award_result_source UNIQUE (award_result_id, source_id)
);

CREATE TABLE case_source (
    id            INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- surrogate technical PK
    case_id       INTEGER     NOT NULL REFERENCES case_project(case_id) ON DELETE CASCADE,
    source_id     INTEGER     NOT NULL REFERENCES source(source_id)     ON DELETE CASCADE,
    relation_type VARCHAR(20) CHECK (relation_type IS NULL OR relation_type IN ('primary','supplementary')),
    CONSTRAINT uq_case_source UNIQUE (case_id, source_id)
);

CREATE INDEX idx_library_source_source ON library_source(source_id);
CREATE INDEX idx_award_source_source   ON award_source(source_id);
CREATE INDEX idx_ar_source_source      ON award_result_source(source_id);
CREATE INDEX idx_case_source_source    ON case_source(source_id);
CREATE INDEX idx_country_source_source ON country_source(source_id);

COMMIT;
