-- ============================================================
-- 由 db/seed/generate-seed.py 自动生成 —— 请勿手改
-- 生成时间：2026-10-03 11:46:36
-- 数据源：data/awards.json、data/award-results.json、data/cases.json、data/sources.json、data/country-source.json、data/library-source.json、data/award-source.json、data/award-result-source.json、data/case-source.json（Stage8-v1.0 冻结基线）
-- Award = 5（published 5）
-- Award_Result = 69（pending 3 / published 66）
-- Case_Project = 10（pending 2 / published 8）
-- Source = 64（published 64）
-- country_source = 33；library_source = 99；award_source = 18；award_result_source = 103；case_source = 22
-- 显式写出主键 ID，保证与 JSON 一致
-- ============================================================

BEGIN;

-- ---------- Award ----------
INSERT INTO award (award_id, award_name, organizer, description, official_website, founded_year, frequency, status, last_updated, created_at) VALUES (1, 'IFLA Public Library of the Year（年度公共图书馆奖）', '国际图书馆协会和机构联合会（IFLA），2014年与丹麦文化署合作发起', '表彰全球最佳新建公共图书馆，奖金5000美元；参评馆须为新建、显著扩建或设于非图书馆用途建筑，且于评选上一年度建成开放。历届获奖：2014 Craigieburn（澳大利亚）、2015 Kista（瑞典）、2016 Dokk1（丹麦）、2018 School 7（荷兰）、2019 Oodi（芬兰）、2021 Deichman Bjørvika（挪威）、2022 Missoula（美国）、2023 加西亚·马尔克斯（西班牙）、2024 北京城市图书馆（中国）、2025 加布里埃尔·罗伊（加拿大）。2017年未颁奖；2020年官网名单无获奖记录，原因待核实。', 'https://www.ifla.org/g/public-libraries/public-library-of-the-year-award/', 2014, 'annual', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award (award_id, award_name, organizer, description, official_website, founded_year, frequency, status, last_updated, created_at) VALUES (2, 'IFLA Green Library Award（绿色图书馆奖）', '国际图联环境、可持续发展与图书馆专业组（ENSULIB）', '2016年设立，表彰在环境可持续性与社会价值融合方面表现卓越的图书馆与项目。奖项设两个平行类别：Best Green Library / Grand Scale Project（大型馆或整体改造项目）与 Best Green Library Project（专项绿色项目），各类别独立评出 1st / 2nd / 3rd。首届（2016）获奖者为墨西哥恰帕斯州小太阳生态图书馆；历届获奖机构覆盖亚洲、欧洲、北美、南美、非洲与大洋洲六大洲。2025年为第十届，22个国家41家图书馆参评；2026年第十一届收到27个国家62份申报材料。', 'https://www.ifla.org/?p=247173', 2016, 'annual', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award (award_id, award_name, organizer, description, official_website, founded_year, frequency, status, last_updated, created_at) VALUES (3, 'IFLA PressReader International Library Marketing Award（国际营销奖）', '国际图联管理与营销专业组（IFLA Section on Management and Marketing）', '图书馆营销领域国际奖项，表彰富于创造性、以结果为导向的营销活动。前三名分获奖金（2024年：3000/2000/1500欧元；2025年：3500/2500/2000欧元），前十名获嘉许证书与 PressReader 高级账户。首届（2002）由美国休斯敦公共图书馆获得；已知历届获奖机构覆盖亚洲、欧洲、北美、南美、非洲与大洋洲六大洲，中国机构（清华大学图书馆、上海图书馆、佛山市图书馆、厦门大学图书馆、北京科技大学图书馆、北京大学附属小学图书馆、南京大学图书馆等）多次获奖。2024年收到107份申报；2025年收到近100份申报。', 'https://www.ifla.org/ifla-pressreader-international-marketing-award/', NULL, 'annual', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award (award_id, award_name, organizer, description, official_website, founded_year, frequency, status, last_updated, created_at) VALUES (4, 'AIA/ALA Library Building Award（图书馆建筑奖）', '美国建筑师学会（AIA）与美国图书馆协会（ALA）Core 分会', '1962年由 AIA、ALA 与国家图书委员会共同设立，是唯一以整座图书馆建筑及其设计全维度为评审对象的奖项；面向所有允许公众进入的图书馆类型，项目可位于世界任何地区。评审关注场所感、目的性、生态与环境可持续性及历史延续性，2025年由11人评审团评出5个获奖项目。', 'https://www.aia.org/design-excellence/award-winners/aiaala-library-building-award-2025', 1962, 'biennial', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award (award_id, award_name, organizer, description, official_website, founded_year, frequency, status, last_updated, created_at) VALUES (5, 'Gale/LJ Library of the Year（年度图书馆奖）', '《Library Journal》（与 Gale 合作赞助）', '由美国图书馆行业媒体《Library Journal》评选的年度公共图书馆奖项，表彰在社区服务、创新与公平方面表现卓越的图书馆系统。近年获奖者包括：2017 纳什维尔公共图书馆、2018 旧金山公共图书馆、2019 洛杉矶县图书馆、2020 西雅图公共图书馆、2021 阿纳海姆公共图书馆。', 'https://www.libraryjournal.com/section/libraryoftheyear', NULL, 'annual', 'published', '2026-09-19', '2026-09-19T04:00:00');

-- ---------- Award_Result（依赖 award / library，见 02） ----------
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (1, 1, 17, 2016, 'general', 'winner', NULL, '2016年8月于美国哥伦布市 IFLA 年会颁发；从4个入围馆中选出，为首个获奖的丹麦图书馆。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (2, 1, 1, 2023, 'general', 'shortlist', NULL, '2023年度四个入围馆之一（另三个为巴塞罗那加西亚·马尔克斯图书馆〔获奖〕、悉尼帕拉马塔 PHIVE 图书馆、斯洛文尼亚瓦尔瓦索尔图书馆）；参赛馆来自11国共16家。获奖主体为上图东馆（该馆新建建筑），记录归入上海图书馆。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (3, 1, 4, 2024, 'general', 'winner', NULL, '2024年10月7日于西班牙巴塞罗那 IFLA 中期会议颁发；从10国16馆中选出，中国图书馆首次获此奖项。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (4, 3, 9, 2023, 'general', 'runner_up', 'Books Unbanned（图书解禁）', '2023年国际图联国际营销奖第二名。项目针对美国图书禁令与审查挑战，面向全美13-21岁青少年提供布鲁克林公共图书馆数字资源免费访问。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (5, 3, 1, 2024, 'general', 'winner', 'RPR: Immersed in Classics Literature（沉浸式经典阅读）', '2024年国际图联国际营销奖前十名优胜项目（前十名以 winner 记录，名次信息见描述）。由悬疑作家将中外经典小说改编为沉浸式阅读剧本，参与者扮演角色互动阅读。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (6, 2, 5, 2025, 'Best Green Library / Grand Scale Project', 'runner_up', '生长图书馆：万物皆可读，万物皆生长（The Growth Library）', '第十届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第二名（第一名：巴黎詹姆斯·鲍德温图书馆；第三名：纳什维尔公共图书馆唐森分馆）；本届本类别亚洲唯一获奖大型项目，从22国41馆中选出。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (7, 1, 24, 2014, 'general', 'winner', NULL, '首届 IFLA 年度公共图书馆奖得主，2014年8月在法国里昂 IFLA 年会上颁发；同期入围馆包括伯明翰图书馆、荷兰书山图书馆与丹麦 Ørestad 图书馆。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (8, 1, 23, 2015, 'general', 'winner', NULL, '2015年 IFLA 年度公共图书馆奖得主（瑞典斯德哥尔摩 Kista 公共图书馆）。', 'pending', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (9, 1, 22, 2018, 'general', 'winner', NULL, '2018年于马来西亚吉隆坡 IFLA 年会颁发；从19国35家申报馆中选出5个入围馆后获奖，评审特别肯定其与本地伙伴的合作与“社区客厅”定位。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (10, 1, 19, 2019, 'general', 'winner', NULL, '2019年 IFLA 年度公共图书馆奖得主；开放首年接待310万访客，显著超出预期并带动赫尔辛基全市图书馆到访量增长。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (11, 1, 20, 2021, 'general', 'winner', NULL, '2021年 IFLA 年度公共图书馆奖得主；该馆2020年6月18日开放，按被动房标准建造。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (12, 1, 10, 2022, 'general', 'winner', NULL, '2022年 IFLA/Systematic 年度公共图书馆奖得主；评审称其“兼具优美建筑与丰富的服务可能，同时作为社区聚会场所”，系美国首个专为 kulturhus 理念建造的图书馆。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (13, 1, 18, 2023, 'general', 'winner', NULL, '2023年于荷兰鹿特丹颁发；为西班牙图书馆首次入围并获奖，馆长 Neus Castellano 代表领奖。', 'pending', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (14, 1, 21, 2025, 'general', 'winner', NULL, '2025年8月18日于哈萨克斯坦阿斯塔纳第89届世界图书馆与信息大会颁发；评审团肯定其以社区为中心的改造与扩建策略及广泛的可持续措施，同期入围馆为中国上海和平书院、美国 New Canaan Library。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (15, 2, 13, 2025, 'Best Green Library / Grand Scale Project', 'other', 'Retro Roots, Green Future: A Midcentury Marvel in Sustainability', '第十届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第三名，获奖主体为2024年6月开放的 Donelson 分馆（LEED 金级认证，含地热系统与屋顶光伏）。注：result_type 枚举暂无“第三名”细分值，暂记 other，名次信息以描述为准（该枚举扩展属 Future，需另行评审）。', 'pending', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (16, 2, 6, 2026, 'Best Green Library / Grand Scale Project', 'runner_up', '绿荫里图书馆（Greenwood Neighborhood Library）', '第11届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别全球第二名（第一名：土耳其伊斯坦布尔拉米图书馆；第三名：爱尔兰芒斯特理工大学特拉利校区图书馆），为本届该类别唯一获奖的中国图书馆机构，从27国62份申报材料中选出。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (17, 3, 11, 2025, 'general', 'winner', 'March Meowness（三月猫咪通行证）', '2025年 IFLA PressReader 国际营销奖第一名。活动接受用户提交猫咪照片以抵扣逾期罚款，评审认为其“证明高影响力不一定需要大量资金，而需要创造力”，活动逻辑、影响陈述与评估方法清晰。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (18, 3, 4, 2025, 'general', 'runner_up', 'Reading Garden（阅读花园）', '2025年 IFLA PressReader 国际营销奖第二名，由北京城市图书馆与首都图书馆共同申报；活动通过线上追踪、应用程序与馆内花园墙结合，连接阅读与数字空间，评审特别肯定家长阅读习惯对儿童的带动作用。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (19, 4, 10, 2023, 'general', 'winner', 'Missoula Public Library New Main Library', '2023年 AIA/ALA 图书馆建筑奖五个获奖项目之一；项目造价约3800万美元，由 MSR Design 与 A&E Design 设计，整座建筑被构想为“社区客厅”。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (20, 4, 14, 2023, 'general', 'winner', 'Atherton Library', '2023年 AIA/ALA 图书馆建筑奖五个获奖项目之一，由 WRNS Studio 设计，以零净能耗建筑回应现代图书馆作为社区枢纽的转型。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (21, 4, 15, 2023, 'general', 'winner', 'Woburn Public Library', '2023年 AIA/ALA 图书馆建筑奖五个获奖项目之一，由 CBT 设计，在保留原历史建筑的基础上新增约3.05万平方英尺。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (22, 5, 13, 2017, 'general', 'winner', NULL, '2017年 Gale/LJ 年度图书馆；评审认为其在项目、服务与馆藏广度，以及与公共部门、本地企业的合作方面均可作为全国与全球的典范。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (23, 5, 12, 2018, 'general', 'winner', NULL, '2018年 Gale/LJ 年度图书馆；评审称其为全球公共图书馆的典范与灵感来源。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (24, 2, 25, 2016, 'Best Green Library / Grand Scale Project', 'winner', '小太阳生态图书馆（The Little Sun Ecological Library）', '首届 IFLA 绿色图书馆奖第一名。项目由学生家长发起、学校组织，以回收纸板、PET 塑料瓶、废金属与木材等材料共建生态图书馆，并以此开展阅读与环保教育。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (25, 2, 27, 2016, 'Best Green Library / Grand Scale Project', 'other', '土地为播种者（The land is for those who sow）', '首届 IFLA 绿色图书馆奖第三名。麦德林公共图书馆系统在馆区周边开展土地绿化与可食用植物种植，由社区参与维护。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (26, 2, 26, 2017, 'Best Green Library / Grand Scale Project', 'winner', '收获你的城市（Ernte deine Stadt / Harvest Your City）', '第二届 IFLA 绿色图书馆奖第一名。市图书馆以三年期的绿色与可持续承诺，融合城市园艺、创客空间与社区营造，并促成当地首个社区支持农业项目。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (27, 2, 28, 2017, 'Best Green Library / Grand Scale Project', 'runner_up', '从绿色图书馆到可持续图书馆（From a Green Library to a Sustainable Library）', '第二届 IFLA 绿色图书馆奖并列第二名。馆舍按生态环保理念改造为绿色图书馆，并以展览与活动推动公众环境教育。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (28, 2, 29, 2017, 'Best Green Library / Grand Scale Project', 'runner_up', '不仅仅是一座绿色建筑——将绿色战略融入香港中文大学图书馆', '第二届 IFLA 绿色图书馆奖并列第二名。将可持续发展纳入图书馆战略，形成超出单幢绿色建筑的绿色策略。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (29, 2, 42, 2017, 'Best Green Library / Grand Scale Project', 'runner_up', '图书馆阅读树（Library Reading Tree）', '第二届 IFLA 绿色图书馆奖并列第二名。自 2015 年起在纳库鲁地区六所公立小学建立儿童读书会，以“阅读树”涂鸦激励儿童阅读。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (30, 2, 30, 2018, 'Best Green Library / Grand Scale Project', 'winner', '佛山市图书馆的绿色实践（Foshan Library''s Green Practice）', '第三届 IFLA 绿色图书馆奖第一名。评审认为其建筑与景观相协调，可持续原则贯穿建筑设计、材料、管理与社区教育，并形成面向社区的绿色活动体系。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (31, 2, 31, 2019, 'Best Green Library / Grand Scale Project', 'winner', '盖亚——在我的图书馆里，地球也属于所有人（Gaia）', '第四届 IFLA 绿色图书馆奖第一名。以生态与社会责任并重的方式服务社区多元群体，并将可持续与社区经济议题纳入项目。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (32, 2, 32, 2020, 'Best Green Library / Grand Scale Project', 'winner', '埃德蒙顿公共图书馆（Edmonton Public Library）', '第五届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。以可持续运营与社区服务的结合获得评审肯定。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (33, 2, 33, 2020, 'Best Green Library Project', 'winner', '兰实大学图书馆与可持续环境管理报告（Rangsit University Library and Sustainable Environment Management Report）', '第五届 IFLA 绿色图书馆奖项目类别第一名。以可持续环境管理报告参评，覆盖资源使用、废弃物管理与环境教育。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (34, 2, 34, 2020, 'Best Green Library Project', 'runner_up', '守卫我们的城市——杭州图书馆环保分馆的绿色使命', '第五届 IFLA 绿色图书馆奖项目类别并列第二名。通过设立环保分馆推动城市环境教育。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (35, 2, 35, 2020, 'Best Green Library / Grand Scale Project', 'other', '坪山图书馆的绿色行动（Green Efforts of Pingshan Library）', '第五届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别短名单。以绿色建筑设计与阅读推广结合的实践入围。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (36, 2, 36, 2021, 'Best Green Library / Grand Scale Project', 'winner', '负责任的图书馆是环保意识的推动者（A Responsible Library as Promoter of Environmental Awareness）', '第六届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。环保实践覆盖馆藏、能源使用与物流，并制定可持续发展行动计划。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (37, 2, 37, 2022, 'Best Green Library / Grand Scale Project', 'winner', '蔡厝港公共图书馆更新（Revamp of Choa Chu Kang Public Library）', '第七届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。改造后以可持续设计整合学习体验、社区服务与绿色空间。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (38, 2, 38, 2022, 'Best Green Library Project', 'winner', '卡诺埃佩尔媒体图书馆：巴黎网络可持续发展试点图书馆', '第七届 IFLA 绿色图书馆奖项目类别第一名。作为巴黎公共图书馆网络的可持续发展试点，围绕可持续议题提供服务与活动。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (39, 2, 39, 2023, 'Best Green Library / Grand Scale Project', 'winner', 'EPM 图书馆——可持续发展教育（EPM Biblioteca - Education for Sustainable Development）', '第八届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。以可持续发展教育为核心战略，贯穿活动、计划、机器人与技术。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (40, 2, 40, 2023, 'Best Green Library Project', 'winner', '西温哥华纪念图书馆驻馆气候作家（Climate Writer in Residence）', '第八届 IFLA 绿色图书馆奖项目类别第一名。以驻馆气候作家项目将文化表达与气候议题结合，带动社区参与。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (41, 2, 10, 2024, 'Best Green Library / Grand Scale Project', 'winner', '米苏拉公共图书馆（Missoula Public Library）', '第九届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第一名。新总馆 2021 年开放，以社区客厅定位与可持续设计获奖。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (42, 2, 41, 2024, 'Best Green Library Project', 'winner', '超越生命周期：支持循环经济的图书馆（Beyond the Lifecycle Libraries: Supporting the Circular Economy）', '第九届 IFLA 绿色图书馆奖项目类别第一名。以清晰的目标、广泛的协作与可评价的成效，推动图书馆支持循环经济。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (43, 2, 30, 2024, 'Best Green Library Project', 'other', '绿色阅读：知书达“里”智慧化阅读服务（Green Reading: the intelligent book stacks project）', '第九届 IFLA 绿色图书馆奖项目类别第三名。以智慧书架、线上一站式查询与送书上门等绿色阅读服务参评。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (44, 3, 43, 2002, 'general', 'winner', '读者卡的挑战（The Power Card Challenge）', '首届 IFLA 国际营销奖第一名。以重新设计读者卡、明确营销计划并与社区读者及其监护人建立长期关系为目标，取得良好效果。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (45, 3, 44, 2003, 'general', 'winner', '文学路径（Literary Pathways）', '第二届 IFLA 国际营销奖第一名。通过参观与表演等方式引导非用户走进图书馆，参与名家生活或作品的社区体验活动。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (46, 3, 45, 2004, 'general', 'winner', '我来了，我看见了，我读了（I came, I saw, I read）', '第三届 IFLA 国际营销奖第一名。面向移民与难民家庭儿童开展阅读与计算机素养活动，支持其在文学项目中发展写作与研究技能。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (47, 3, 46, 2006, 'general', 'winner', '我们想念你（We miss you）', '第四届 IFLA 国际营销奖第一名。以低成本、高效益的“提醒”明信片召回低活跃度用户，卡片正面为口号、背面为服务与产品提示。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (48, 3, 47, 2007, 'general', 'winner', '夜间图书馆与妈妈学生图书馆项目（The Night Library and The Mom-Student Library Project）', '第五届 IFLA 国际营销奖第一名。考试周延长服务时间，并为身为父母的学生提供托儿服务。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (49, 3, 48, 2008, 'general', 'winner', '你做完功课了吗？（Have you done your homework?）', '第六届 IFLA 国际营销奖第一名。面向学生开设在线课堂，提供家庭作业辅导。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (50, 3, 37, 2009, 'general', 'winner', 'Go Library', '第七届 IFLA 国际营销奖第一名。以“去图书馆/去儿童图书馆/去虚拟图书馆/去媒体”多平台项目，吸引新老读者体验新加坡的图书馆资源与服务。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (51, 3, 49, 2010, 'general', 'winner', '知识结伴，提升自我（Knowledge Companion to Empower You!）', '第八届 IFLA 国际营销奖第一名。以用户为中心创新信息工具产品线，面向商学院师生推出系列信息工具。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (52, 3, 50, 2011, 'general', 'winner', '试阅者启动项目（Pilots take off-and land）', '第九届 IFLA 国际营销奖第一名。以“在线产品必须在线推广”为原则，围绕两个科学检索门户开展用户宣传。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (53, 3, 3, 2012, 'general', 'winner', '爱上图书馆（Falling in love with the Library）', '第十届 IFLA 国际营销奖第一名。由馆员与学生组成的项目团队制作《爱上图书馆》系列短片并开发“排架也疯狂”小游戏，提升新生对图书馆的利用。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (54, 3, 47, 2013, 'general', 'winner', '会说话的教科书（Talking Textbooks）', '第十一届 IFLA 国际营销奖第一名。由学生志愿者录制音频，针对视力不便的大学生将学习材料数字化，辅助其备考与借还图书。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (55, 3, 51, 2014, 'general', 'winner', '电车上的图书馆（Library in the Tram – Tram to the Library）', '第十二届 IFLA 国际营销奖第一名。与布尔诺公共交通公司及广告代理机构合作，将有轨电车改造为移动的图书馆宣传载体。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (56, 3, 52, 2016, 'general', 'winner', '灵感实验室启动运动（Inspiration Lab Launch Campaign）', '第十三届 IFLA 国际营销奖第一名。建立数字媒体实验室 Inspiration Lab，并通过社交媒体、新闻报道与名人合作开展推广。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (57, 3, 59, 2017, 'general', 'winner', '读书人：见“微”知“著”（READay）', '第十四届 IFLA 国际营销奖第一名。在图书馆官方微信公众号每日推荐书评或书中精彩片段，并邀请用户撰写书评，激发阅读兴趣。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (58, 3, 1, 2017, 'general', 'runner_up', '2016 开放数据应用开发竞赛（Open Data Application Development Contest 2016）', '第十四届 IFLA 国际营销奖并列第二名。以上海图书馆家谱知识数据库为基础，面向全社会征集优秀移动应用原型与服务创意。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (59, 3, 7, 2018, 'general', 'winner', '2017 纽约公共图书馆青少年逾期费豁免（2017 NYC Youth Fine Amnesty）', '第十五届 IFLA 国际营销奖第一名。为 17 岁及以下读者免除逾期罚款并解除借阅限制，通过多渠道营销吸引读者，最终约 4.1 万名青少年重新激活借书卡。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (60, 3, 53, 2019, 'general', 'winner', '凯尔姆斯科特-乔叟数字涂色书活动（Kelmscott Chaucer Digital Colouring Book campaign）', '第十六届 IFLA 国际营销奖第一名。将馆藏珍品《乔叟集》数字化并选取精图制成数字涂色书，以话题标签在社交媒体推广馆藏。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (61, 3, 30, 2020, 'general', 'winner', '邻里图书馆（N-Library: To Forge a Closer Community）', '第十七届 IFLA 国际营销奖第一名。自 2018 年起推进“千家万户”温暖工程，将公共图书馆资源“搬进”市民家中，建立“微型图书馆”，以邻里关系为纽带输送阅读服务。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (62, 3, 54, 2021, 'general', 'winner', '绝世食谱（The Monash and Penn State Great Rare Books Bake Off）', '第十八届 IFLA 国际营销奖第一名（与宾夕法尼亚州立大学图书馆共同获奖）。邀请参与者烘焙馆藏特色食谱并发布到社交媒体，疫情期间提供创意性的公众参与渠道。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (63, 3, 55, 2021, 'general', 'winner', '绝世食谱（The Monash and Penn State Great Rare Books Bake Off）', '第十八届 IFLA 国际营销奖第一名（与莫纳什大学图书馆共同获奖）。以馆藏珍本食谱为线索开展社交媒体互动，吸引公众关注特藏资源。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (64, 3, 56, 2022, 'general', 'winner', '我们在为下一阶段做准备，请写下自己的声音（We''re ready for the next chapter. Help us write it）', '第十九届 IFLA 国际营销奖第一名。通过在线调查、研讨论坛、在地公园与市场的快闪活动及图书馆装置，收集社区意见用于战略规划。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (65, 3, 60, 2022, 'general', 'runner_up', '点亮图书馆（Illuminating Our Library）', '第十九届 IFLA 国际营销奖并列第二名。以游戏化方式在全校开展信息素养教育活动，学生参与各类主题探索任务并创作阅读成长手册。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (66, 3, 27, 2023, 'general', 'winner', '环游世界，走遍 26 个图书馆（Around the World in 26 Libraries）', '第二十届 IFLA 国际营销奖第一名。将 26 个国家的文化元素融入图书馆总馆与分馆，读者在线注册领取“旅行日记”后到馆盖章，以“旅行者”机制激励到访。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (67, 3, 30, 2023, 'general', 'other', '易本书（Ex-Book: Old Flame, New Joy）', '第二十届 IFLA 国际营销奖第三名。基于微信生态构建家庭藏书交换平台，市民可上传闲置书籍、借阅他人藏书，以数字方式促成家庭图书流转。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (68, 3, 57, 2024, 'general', 'winner', '拥有图书证的 100 个理由（100 reasons to have a library card）', '第二十一届 IFLA 国际营销奖第一名。通过调研与用户反馈筛选出 100 条具代表性的办证理由并整合为宣传材料，活动后到访的新读者占比约 61%。', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO award_result (award_result_id, award_id, library_id, year, category, result_type, project_name, description, status, last_updated, created_at) VALUES (69, 3, 61, 2024, 'general', 'other', '图书馆的声音（The sounds of the library）', '第二十一届 IFLA 国际营销奖第三名。师生携手创作歌曲，将图书馆中采集的 9 种真实声音融入编曲，以诙谐歌词吸引学生关注并改善在馆行为习惯。', 'published', '2026-09-19', '2026-09-19T04:00:00');

-- ---------- Case_Project ----------
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (1, 7, 'Insta Novels（Insta 小说）', 'digital_service', '2018年8月22日启动，与创意机构 Mother New York 合作，将《爱丽丝梦游仙境》等公版经典做成 Instagram Stories 数字小说：拇指按住屏幕定格、抬起翻页，Highlights 成为数字书架；上线一个月内 @nypl 涨粉超8.9万，SimplyE 应用下载量显著上升。该项目重新定义了社交媒体平台上的长文阅读。', 2018, 'https://www.nypl.org/instanovels', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (2, 9, 'Books Unbanned（图书解禁计划）', 'accessibility_inclusion', '2021年4月发起，针对美国日益增多的图书禁令与审查挑战，面向全美13-21岁青少年免费开放布鲁克林公共图书馆数字馆藏与学习数据库，增强青少年捍卫阅读自由的能力；2023年获 IFLA 国际营销奖第二名。', 2021, 'https://www.bklynlibrary.org/books-unbanned', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (3, 1, 'RPR 沉浸式经典阅读（Immersed in Classics）', 'reading_promotion', '上海图书馆东馆推出的沉浸式阅读体验项目：由悬疑作家将中外经典小说改编为沉浸式阅读剧本，参与者在同一空间内扮演角色、依剧本互动，融合年轻人喜爱的剧本元素推广经典阅读；2024年获 IFLA 国际营销奖前十名。', 2023, NULL, 'pending', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (4, 4, '北京城市图书馆：世界最大恒温阅览空间的绿色实践', 'space_architecture', '2023年12月开放的智慧复合型图书馆：建筑面积约7.5万平方米，世界最大单体恒温阅览空间；阶梯式平台设计呼应通惠河河谷景观，采用模块化组件、气候控制、雨水回收等可持续方案，达中国绿色建筑三星标准；2024年获 IFLA 年度公共图书馆奖。', 2023, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (5, 5, '生长图书馆（The Growth Library）', 'sustainability', '2024年开放于盐田区生物圈三号·大梅沙万科中心碳中和实验园区：屋顶光伏满足85%能源需求、智能遮阳降低60%空调能耗、配套雨水回收系统，年减碳约800吨；设海洋图书馆、黑水虻厨余工坊、屋顶生态花园等“绿色+”场景，并发起联合141城2721家图书馆的“盐田倡议”。获2025年 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别第二名。', 2024, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (6, 19, 'Oodi：面向全民的公民客厅与共创服务', 'community_service', 'Oodi 以“城市的客厅”为定位，三层空间分别对应活跃的城市广场、多功能中间层与宁静的阅读层；公民阳台正对议会大厦，象征图书馆与公众、民主之间的联结；建筑按近零能耗（nZEB）标准建造，并使用本地材料与被动式太阳能设计。服务由自组织团队与市民共创持续迭代，开放首年接待310万访客，并带动赫尔辛基全市图书馆到访量与办证量增长。', 2018, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (7, 20, 'Deichman Bjørvika：城市文化客厅与被动房建筑实践', 'space_architecture', '六层空间内含影院、200座报告厅、录音棚、游戏室、儿童区与 Future Library 艺术项目，藏量约45万册，总建筑面积1.96万平方米（净1.356万平方米）；按被动房标准建造，在立面、通风与材料使用上采用创新方案；首层全透明立面设有三个方向的入口，使图书馆向城市完全开放。2021年获 IFLA 年度公共图书馆奖。', 2020, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (8, 18, '加西亚·马尔克斯图书馆：拉美文学社区空间', 'community_service', '2022年5月28日开馆，六层约4000平方米，为巴塞罗那第三大图书馆；以交错层压木（CLT）为主要结构，营造温暖氛围并降低环境足迹，外立面形似一摞打开的书；专藏拉丁美洲文学，并保存本地漫画家 Francisco Ibáñez 的档案；2023年获 IFLA 年度公共图书馆奖，评审称其“像家一样欢迎人”。', 2022, NULL, 'pending', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (9, 21, 'Gabrielle-Roy 图书馆：既有建筑更新与十个主题枢纽', 'space_architecture', '2024年2月开放，由 Saucier + Perrotte 与 GLCRM 建筑事务所联合设计；通过改造并扩建既有结构、最大限度减少拆除与新建材料需求体现可持续策略；四层设十个主题枢纽（音乐与电影、青少年、烹饪等），源于与社区共同设计的流程，覆盖沉浸式学习、休憩与创作等不同功能，被评审视为适配多元社区的“第三空间”。2025年获 IFLA 年度公共图书馆奖。', 2024, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO case_project (case_id, library_id, title, topic, description, year, project_url, status, last_updated, created_at) VALUES (10, 6, '绿荫里图书馆：旧屋微改造的乡村绿色图书馆', 'sustainability', '2025年3月对外开放，由英林镇长存公园内闲置旧屋微改造而成，完整保留旧屋结构与红砖风貌，通过增设大面积采光玻璃将自然景观引入室内，并依托长存公园3.7万平方米林地调节气候，全年降低建筑能耗约40%；以1000平方米空间服务30平方公里范围内8.25万名常住居民，形成“政府主导、图书馆运营、社会参与、居民共建”四位一体机制；纳入晋江市级总分馆体系，共享全市272万册纸质图书，每年节省购书经费13.6万元，服务延伸至28所中小学；开馆至今接待读者6.85万人次、新增读者证3792张。2026年获第11届 IFLA 绿色图书馆奖“最佳绿色图书馆/大型项目”类别全球第二名。', 2025, NULL, 'published', '2026-09-19', '2026-09-19T04:00:00');

-- ---------- Source ----------
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (1, 'IFLA 官方网站', 'international_organization', 'IFLA/James Bennett Public Library of the Year Award（奖项页，含历届获奖名单）', 'https://www.ifla.org/g/public-libraries/public-library-of-the-year-award/', 'IFLA', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (2, 'IFLA 2023 世界图书馆与信息大会官网', 'international_organization', 'IFLA/Systematic Public Library of the Year Award 2023 Winner announced', 'https://2023.ifla.org/ifla-systematic-public-library-of-the-year-award-2023-winner-announced/', 'IFLA', '2023-08-21', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (3, 'Danmarks Biblioteksforening（丹麦图书馆协会）', 'library_association', 'Public Library of the Year Award 2016（Dokk1 获奖评述）', 'https://db.dk?p=18576/', 'Danmarks Biblioteksforening', NULL, '2026-09-19', 'da', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (4, 'Licitations（丹麦建筑行业媒体）', 'news', 'Dokk1 er verdens bedste folkebibliotek', 'https://www.licitationen.dk/article/view/288121/dokk1_er_verdens_bedste_folkebibliotek', 'Licitations', NULL, '2026-09-19', 'da', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (5, 'World Architecture Community', 'other', 'Schmidt Hammer Lassen Architects'' Dokk1 wins Public Library of the Year Award 2016', 'https://worldarchitecture.org/architecture-news/cgzem/schmidt-hammer-lassen-architects-dokk1-wins-public-library-of-the-year-award-2016.html', 'World Architecture Community', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (6, 'Aarhus Bibliotekerne（奥胡斯图书馆官网）', 'official_website', 'Torvet og Demokrateket（Dokk1 开放空间页）', 'http://www.aakb.dk/node/71', 'Aarhus Bibliotekerne', NULL, '2026-09-19', 'da', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (7, 'The Guardian（卫报）', 'news', 'Sydney entry beaten by ''spectacular'' Beijing building in library of the year award', 'https://www.theguardian.com/culture/2024/oct/08/sydney-entry-beaten-by-spectacular-beijing-building-in-library-of-the-year-award', 'The Guardian', '2024-10-08', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (8, '腾讯新闻', 'news', '国际图联专委会委员："看到中国获奖，我仿佛看到图书馆的未来"', 'https://news.qq.com/rain/a/20250414A09ES500', '腾讯新闻', '2025-04-14', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (9, 'IFLA 官方新闻稿（PDF）', 'international_organization', 'IFLA PressReader International Marketing Award Winners 2024', 'https://cdn.ifla.org/wp-content/uploads/Media-Release_IFLA-PressReader-International-Marketing-Award-Winners-2024-2605.pdf', 'IFLA', '2024-05-26', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (10, 'IFLA 官方网站', 'international_organization', 'IFLA PressReader International Library Marketing Award（奖项页）', 'https://www.ifla.org/ifla-pressreader-international-marketing-award/', 'IFLA', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (11, '南京图书馆官网', 'official_website', '国际资讯：2024年国际图联国际营销奖获胜者揭晓，中国四家图书馆上榜前十', 'https://www.jslib.org.cn/zx/yjzx/gj/202406/t20240621_286673.html', '南京图书馆', '2024-06-21', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (12, 'e线图情（图书馆行业资讯平台）', 'other', '2023年国际图联国际营销奖获胜者揭晓，中国多家图书馆上榜', 'http://e.zslib.com.cn/organ/Detail?newId=115880', 'e线图情', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (13, 'IFLA 官方网站', 'international_organization', '10th IFLA Green Library Award 2025 results announced!', 'https://www.ifla.org/?p=247173', 'IFLA', '2025-08-19', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (14, '人民网深圳频道', 'news', '深圳盐田"生长图书馆"获国际大奖', 'https://sz.people.com.cn/n2/2025/0822/c202846-41330029.html', '人民网', '2025-08-22', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (15, '南方+（南方新闻网）', 'news', '盐田区图书馆摘得国际图联"绿色图书馆奖"', 'https://www.nfnews.com/content/5yppZw24yp.html', '南方日报', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (16, '中华人民共和国文化和旅游部', 'government', '国家图书馆（单位简介）', 'https://www.mct.gov.cn/preview/gywhb/jgsz/zsdw_jgsz/202311/t20231116_949743.htm', '文化和旅游部', '2023-11-16', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (17, '国家图书馆读者云门户', 'official_website', '国图概况（沿革与馆舍）', 'http://read.nlc.cn/ReaderGuide/GTgk', '国家图书馆', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (18, '清华大学官网', 'official_website', '图书馆（学校简介-图书馆页）', 'https://www.tsinghua.edu.cn/info/1360/1391.htm', '清华大学', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (19, '清华大学图书馆官网', 'official_website', '馆长致辞（建馆110周年）', 'https://lib.tsinghua.edu.cn/anniversary110/gzzc.htm', '清华大学图书馆', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (20, 'The New York Public Library 官网', 'official_website', 'About The New York Public Library', 'https://www.nypl.org/about', 'The New York Public Library', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (21, 'The New York Public Library 官网', 'official_website', 'Read NYPL Insta Novels（项目页）', 'https://www.nypl.org/instanovels', 'The New York Public Library', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (22, 'The New York Public Library 官网', 'official_website', 'The New York Public Library introduces classic literature to "Instagram Stories" with Insta Novels（新闻稿）', 'https://www.nypl.org/press/new-york-public-library-introduces-classic-literature-instagram-stories-insta-novels', 'The New York Public Library', '2018-08-22', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (23, 'Library Journal（图书馆行业媒体）', 'news', 'Insta Novels an Instant Social Media Hit for NYPL', 'https://www.libraryjournal.com/story/Re/180917NYPLinsta', 'Library Journal', '2018-09-17', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (24, 'Brooklyn Public Library 官网', 'official_website', 'About Brooklyn Public Library', 'https://bklynlibrary.org/about', 'Brooklyn Public Library', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (25, 'Brooklyn Public Library 官网', 'official_website', 'Our 125th Anniversary（1896年11月30日决议建馆）', 'https://www.bklynlibrary.org/125', 'Brooklyn Public Library', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (26, 'Brooklyn Public Library 年度报告（PDF）', 'official_website', 'Annual Report 2022 & 23', 'https://static.bklynlibrary.org/prod/public/inline-documents/Annual%20Report%20FY22-23%20Web.pdf', 'Brooklyn Public Library', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (27, 'Library of Congress 官网', 'official_website', 'Library of Congress Fact Sheet（1800年4月24日建立）', 'https://www.loc.gov/item/prn-16-a05/library-of-congress-fact-sheet/2016-09-01/', 'Library of Congress', '2016-09-01', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (28, 'Royal Danish Library 官网', 'official_website', 'Timeline for Royal Danish Library（1648年奠基、2017年合并）', 'https://www.kb.dk/en/node/186', 'Royal Danish Library', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (29, '上海图书馆官网', 'official_website', '2022年9月28日，上海图书馆东馆正式开馆', 'https://www.library.sh.cn/article/91234', '上海图书馆', '2022-09-28', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (30, '上海图书馆官网', 'official_website', '上海图书馆首页（淮海路馆/东馆体系）', 'https://www.library.sh.cn/', '上海图书馆（上海科学技术情报研究所）', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (31, '腾讯新闻', 'news', '有了东馆，70岁的上海图书馆，未来还"在路上"', 'https://news.qq.com/rain/a/20221006A07Q2H00', '腾讯新闻', '2022-10-06', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (32, '中国图书馆学会', 'library_association', '对外交流（国际图联奖项申报信息与历届中国馆入围获奖情况）', 'https://www.lsc.org.cn/cns/html_pass/channels/1097.html', '中国图书馆学会', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (33, '巴塞罗那市政府图书馆网站', 'government', 'Biblioteca Gabriel García Márquez short-listed for the IFLA''s 2023 Best Public Library Award（含四入围馆名单）', 'https://ajuntament.barcelona.cat/biblioteques/en/news/biblioteca-gabriel-garcia-marquez-short-listed-for-the-iflas-2023-best-public-library-award-1296767', 'Ajuntament de Barcelona', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (34, 'Danmarks Biblioteksforening（丹麦图书馆协会）', 'library_association', 'Hvem bliver Public Library of the Year?（2023四入围馆介绍）', 'https://db.dk/bladartikel/hvem-bliver-public-library-of-the-year/', 'Danmarks Biblioteksforening', NULL, '2026-09-19', 'da', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (35, 'IFLA 官方网站', 'international_organization', 'IFLA/Baker & Taylor Public Library of the Year Award 2025 announced', 'https://www.ifla.org/?p=247141', 'IFLA', '2025-08-18', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (36, 'IFLA 官方网站', 'international_organization', 'Dutch library named the world''s best new public library in 2018（School 7 / KopGroep 获奖公告）', 'https://www.ifla.org/news/dutch-library-named-the-world-s-best-new-public-library-in-2018', 'IFLA', '2018-08-28', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (37, 'Designing Libraries（英国图书馆设计信息平台）', 'other', 'The world''s best new library 2018（含 2014-2016 历届获奖名单与 2017 年未颁奖说明）', 'https://designinglibraries.org.uk/index.asp?PageID=1543', 'Designing Libraries', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (38, 'Designing Libraries（英国图书馆设计信息平台）', 'other', 'Public Library of the Year Award — Craigieburn Library 2014（含入围名单与评审理由）', 'https://designinglibraries.org.uk/index.asp?PageID=513', 'Designing Libraries', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (39, 'bbn adviseurs（荷兰建筑咨询机构）', 'other', 'Bibliotheek School 7 Den Helder wint Public Library of The Year award（含 2016 年开放与 1905 年老校舍沿革）', 'https://bbn.nl/bibliotheek-school-7-den-helder-wint-public-library-of-the-year-award', 'bbn adviseurs', NULL, '2026-09-19', 'nl', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (40, 'Design Helsinki（赫尔辛基市设计官网）', 'government', 'Helsinki Central Library Oodi（2018年12月5日开放、首年310万访客、2019 年度公共图书馆奖）', 'https://design.hel.fi/en/design-stories/central-library-oodi/', 'City of Helsinki', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (41, 'European Commission — Culture and Creativity', 'government', 'Helsinki Central Library Oodi（Living Spaces 案例：nZEB 近零能耗、17,100㎡、预算约9,300万欧元）', 'https://culture.ec.europa.eu/cultural-and-creative-sectors/architecture/living-spaces/catalogue/helsinki', 'European Commission', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (42, 'Atelier Oslo（建筑事务所官网）', 'other', 'Deichman Bjørvika（2020年6月18日对公众开放、被动房标准、2021 年度公共图书馆奖）', 'https://atelieroslo.no/project/deichman', 'Atelier Oslo', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (43, 'Designing Libraries', 'other', 'Oslo''s new main library（六层功能构成、45万册藏量、19,600㎡ 总建筑面积、Lund Hagem + Atelier Oslo）', 'https://designinglibraries.org.uk/index.asp?PageID=1655', 'Designing Libraries', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (44, 'Deichman（奥斯陆公共图书馆官网）', 'official_website', 'Deichman 官网首页（馆藏、活动与 PressReader 数字报纸服务）', 'https://deichman.no', 'Deichman', NULL, '2026-09-19', 'no', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (45, 'Missoula Public Library 官网', 'official_website', 'Virtual Tour（2021年开放、首个按 kulturhus 理念建造、MSR Design + A&E Design、造价3800万美元）', 'https://www.missoulapubliclibrary.org/home/about/virtual-tour/', 'Missoula Public Library', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (46, 'The Missoula Current（地方新闻）', 'news', 'Missoula Public Library wins national award for best design（2023 AIA/ALA 奖、2022 IFLA 奖、2021年5月开放）', 'http://missoulacurrent.com/missoula-library-design-2/', 'Missoula Current', '2023-05-01', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (47, 'De Gruyter（学术出版）', 'academic', 'Redefining Library as Culture House: The Missoula Public Library Partnership（2022 PLOTY 评审评语、2021年7月开放、106,675 平方英尺）', 'https://www.degruyter.com/document/doi/10.1515/abitech-2023-0003/html', 'De Gruyter', '2023-01-01', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (48, 'AIA（美国建筑师学会）官网', 'official_website', 'Five projects receive 2023 AIA/ALA Library Building Award（含 Missoula / Atherton / Woburn 等5个获奖项目）', 'https://content.aia.org/node/6618060', 'American Institute of Architects', '2023-04-25', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (49, 'AIA（美国建筑师学会）官网', 'official_website', 'AIA/ALA Library Building Award 2025（2025年5个获奖项目；含 Atherton 零净能耗与 Woburn 扩建说明）', 'https://www.aia.org/design-excellence/award-winners/aiaala-library-building-award-2025', 'American Institute of Architects', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (50, 'ALA（美国图书馆协会）官网', 'official_website', 'Five Projects Receive 2025 AIA/ALA Library Building Award（奖项评审范围、11人评审团与评审标准）', 'https://ala.org/news/2025/06/five-projects-receive-2025-aiaala-library-building-award', 'American Library Association', '2025-06-05', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (51, 'American Libraries Magazine', 'news', '2025 ALA/AIA Library Building Awards（获奖机构与建筑师事务所对照名单）', 'https://americanlibrariesmagazine.org/2025/09/02/2025-ala-aia-library-building-awards/', 'American Library Association', '2025-09-02', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (52, 'Library Journal 官网', 'official_website', 'Library Of The Year（历届 Gale/LJ 年度图书馆：2017 Nashville、2018 旧金山、2019 洛杉矶县、2020 西雅图、2021 阿纳海姆）', 'https://www.libraryjournal.com/section/libraryoftheyear', 'Library Journal', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (53, '上海图书馆专业服务门户', 'official_website', '2025年国际图联国际营销奖获胜者名单公布，中国两家图书馆分获二三名（含评审评语与奖金设置）', 'https://eservice.digilib.sh.cn/jbzx/admin/sla/ejb_details.asp?dbID=27752', '上海图书馆', '2025-05-15', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (54, '福建省图书馆官网', 'official_website', '两家中国图书馆进入前三!2025年IFLA PressReader国际营销奖揭晓（含前十名单与英文项目名）', 'https://www.fjlib.net/zx/yjdt/202505/t20250516_478094.htm', '福建省图书馆', '2025-05-16', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (55, 'IFLA 官方网站', 'international_organization', '11th IFLA Green Library Award 2026 results announced!（2026年两个类别完整获奖名单）', 'https://www.ifla.org/news/11th-ifla-green-library-award-2026-results-announced/', 'IFLA', '2026-08-12', '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (56, '中国全民阅读网（国家新闻出版署指导）', 'government', '福建晋江绿荫里图书馆（2025年3月开放、1000㎡、能耗降低约40%、共享272万册、服务28所中小学）', 'https://www.nationalreading.gov.cn/ydkj/202608/t20260828_1005205.html', '中国全民阅读网', '2026-08-28', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (57, '泉州晚报数字报', 'news', '闽南乡村图书馆闪耀国际舞台（IFLA 评审评语、开馆至今6.85万人次、新增读者证3792张）', 'https://szb.qzwb.com/qzwb/pc/cons/202608/14/content_196660.html', '泉州晚报', '2026-08-14', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (58, 'Wikidata', 'other', 'Biblioteca Gabriel García Márquez (Q112194663)（2022-05-28 开馆、2023 IFLA 获奖、隶属巴塞罗那市图书馆网）', 'https://www.wikidata.org/wiki/Q112194663', 'Wikimedia Foundation', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (59, '温州市图书馆官网', 'official_website', 'IFLA 年度公共图书馆奖开放申请（含中文版历届获奖名单：2014-2025）', 'https://www.wzlib.cn/gwdt/39626.html', '温州市图书馆', '2025-03-18', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (60, 'IFLA 官方网站', 'international_organization', 'IFLA Green Library Award 2017 Winners Announced（2017 年得主德国 Stadtbibliothek Bad Oldesloe 及五家并列第二名）', 'https://www.ifla.org/news/ifla-green-library-award-2017-winners-announced', 'IFLA', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (61, 'IFLA 官方网站', 'international_organization', 'IFLA Green Library Award 2018 Winners Announced（2018 年得主中国佛山市图书馆及五家并列第二名）', 'https://www.ifla.org/news/ifla-green-library-award-2018-winners-announced/', 'IFLA', NULL, '2026-09-19', 'en', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (62, '用户提供汇编文档', 'other', '《2016-2024 年国际图联绿色图书馆奖（IFLA Green Library Award）获奖项目》（用户提供的获奖汇总表）', NULL, '用户提供（汇编）', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (63, '用户提供汇编文档', 'other', '《2002-2024 年国际图联国际图书馆营销奖获奖情况》（用户提供的获奖汇总表）', NULL, '用户提供（汇编）', NULL, '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');
INSERT INTO source (source_id, source_name, source_type, title, url, publisher, publication_date, accessed_date, language, status, last_updated, created_at) VALUES (64, '金羊网（羊城派）', 'news', '佛山市图书馆获评全球“最佳绿色图书馆”（2018 年绿色图书馆奖共收到 32 份申请，5 馆并列第二）', 'https://news.ycwb.com/2018-07/21/content_30050267.htm', '羊城晚报报业集团', '2018-07-21', '2026-09-19', 'zh', 'published', '2026-09-19', '2026-09-19T04:00:00');

-- ---------- 来源关联表（无 status 字段，沿用 V0.2 schema） ----------
--        只写业务列 (entity_id, source_id, relation_type)；
--        surrogate id 由 IDENTITY 自动生成，不参与迁移比对。
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (1, 32, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (1, 1, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (1, 56, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (2, 20, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (2, 48, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (3, 28, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (3, 36, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (4, 58, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (4, 2, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (5, 40, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (5, 41, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (6, 42, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (6, 43, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (7, 35, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (8, 36, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (8, 37, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (9, 37, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (10, 38, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (10, 59, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (11, 62, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (12, 62, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (13, 62, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (13, 63, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (14, 62, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (15, 62, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (15, 63, 'supplementary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (16, 62, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (17, 63, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (18, 63, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (19, 63, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (20, 62, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (21, 63, 'primary');
INSERT INTO country_source (country_id, source_id, relation_type) VALUES (22, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (1, 29, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (1, 30, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (1, 31, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (1, 34, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (2, 16, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (2, 17, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (3, 18, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (3, 19, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (4, 7, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (4, 8, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (4, 53, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (4, 54, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (5, 14, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (5, 15, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (5, 13, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (6, 56, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (6, 57, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (6, 55, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (7, 20, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (7, 23, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (8, 27, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (9, 24, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (9, 25, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (9, 26, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (10, 45, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (10, 46, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (10, 47, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (11, 53, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (11, 54, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (12, 52, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (13, 52, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (13, 13, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (14, 48, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (14, 49, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (15, 48, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (15, 49, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (16, 28, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (17, 3, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (17, 6, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (17, 5, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (18, 58, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (18, 2, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (19, 40, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (19, 41, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (20, 44, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (20, 42, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (20, 43, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (21, 35, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (21, 59, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (22, 36, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (22, 39, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (22, 37, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (23, 37, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (23, 59, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (24, 38, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (24, 59, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (25, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (26, 60, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (26, 62, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (27, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (28, 60, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (28, 62, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (29, 60, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (29, 62, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (30, 61, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (30, 62, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (30, 64, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (31, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (32, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (33, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (34, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (35, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (36, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (37, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (37, 63, 'supplementary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (38, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (39, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (40, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (41, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (42, 62, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (43, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (44, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (45, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (46, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (47, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (48, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (49, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (50, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (51, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (52, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (53, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (54, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (55, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (56, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (57, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (58, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (59, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (60, 63, 'primary');
INSERT INTO library_source (library_id, source_id, relation_type) VALUES (61, 63, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (1, 1, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (1, 32, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (1, 35, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (1, 37, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (1, 59, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (2, 13, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (2, 55, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (3, 10, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (3, 11, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (3, 53, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (3, 54, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (4, 48, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (4, 49, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (4, 50, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (4, 51, 'supplementary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (5, 52, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (2, 62, 'primary');
INSERT INTO award_source (award_id, source_id, relation_type) VALUES (3, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (1, 3, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (1, 4, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (1, 5, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (2, 2, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (2, 33, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (2, 34, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (3, 7, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (3, 8, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (4, 12, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (4, 26, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (5, 9, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (5, 11, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (5, 8, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (6, 13, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (6, 14, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (6, 15, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (7, 38, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (7, 37, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (7, 59, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (8, 37, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (8, 59, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (9, 36, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (9, 39, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (10, 40, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (10, 41, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (11, 42, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (11, 43, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (12, 46, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (12, 47, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (12, 45, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (13, 2, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (13, 58, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (14, 35, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (14, 59, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (15, 13, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (16, 55, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (16, 56, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (16, 57, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (17, 53, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (17, 54, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (18, 53, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (18, 54, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (19, 48, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (19, 46, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (19, 47, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (20, 48, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (20, 49, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (21, 48, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (21, 49, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (22, 52, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (23, 52, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (24, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (25, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (26, 60, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (26, 62, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (27, 60, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (27, 62, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (28, 60, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (28, 62, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (29, 60, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (29, 62, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (30, 61, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (30, 62, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (30, 64, 'supplementary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (31, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (32, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (33, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (34, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (35, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (36, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (37, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (38, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (39, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (40, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (41, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (42, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (43, 62, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (44, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (45, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (46, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (47, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (48, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (49, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (50, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (51, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (52, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (53, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (54, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (55, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (56, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (57, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (58, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (59, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (60, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (61, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (62, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (63, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (64, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (65, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (66, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (67, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (68, 63, 'primary');
INSERT INTO award_result_source (award_result_id, source_id, relation_type) VALUES (69, 63, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (1, 21, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (1, 22, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (1, 23, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (2, 26, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (2, 12, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (3, 9, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (3, 8, 'supplementary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (4, 7, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (4, 8, 'supplementary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (5, 13, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (5, 14, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (5, 15, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (6, 40, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (6, 41, 'supplementary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (7, 42, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (7, 43, 'supplementary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (8, 58, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (8, 2, 'supplementary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (9, 35, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (10, 56, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (10, 57, 'primary');
INSERT INTO case_source (case_id, source_id, relation_type) VALUES (10, 55, 'supplementary');

-- identity 序列校正
SELECT setval(pg_get_serial_sequence('award', 'award_id'),
              COALESCE((SELECT MAX(award_id) FROM award), 1));
SELECT setval(pg_get_serial_sequence('award_result', 'award_result_id'),
              COALESCE((SELECT MAX(award_result_id) FROM award_result), 1));
SELECT setval(pg_get_serial_sequence('case_project', 'case_id'),
              COALESCE((SELECT MAX(case_id) FROM case_project), 1));
SELECT setval(pg_get_serial_sequence('source', 'source_id'),
              COALESCE((SELECT MAX(source_id) FROM source), 1));

COMMIT;
